In [1]:
bool(False)

False

In [2]:
mystr = "hjghjg jhukj"  #since space is present false for alnum

In [3]:
mystr.isalnum()   

False

In [4]:
mystr.isalpha()

False

In [5]:
mystr.isdigit()

False

In [6]:
type([])

list

In [7]:
lst = list()
lst

[]

In [8]:
idk = {1: 'dkgj'}

In [9]:
type(idk)

dict

In [10]:
d1 = {'K1' : 1}
d2 = {'K2' : 2}
d3 = {'K3' : 3}

In [11]:
d = {'myK1' : d1, 'myK2' : d2, 'myK3' : d3}

In [12]:
d

{'myK1': {'K1': 1}, 'myK2': {'K2': 2}, 'myK3': {'K3': 3}}

In [13]:
d['myK2']['K2']

2

In [14]:
import numpy as np

In [15]:
type(np.array(1))   #array in ref type

numpy.ndarray

In [16]:
l1 = [6,4,2,5,6]
l2 = [6,7,8,5,6]
l3 = [11,24,32,45,56]
a = np.array([l1, l2, l3])

In [17]:
a.reshape(1,15)

array([[ 6,  4,  2,  5,  6,  6,  7,  8,  5,  6, 11, 24, 32, 45, 56]])

In [18]:
a

array([[ 6,  4,  2,  5,  6],
       [ 6,  7,  8,  5,  6],
       [11, 24, 32, 45, 56]])

In [19]:
a.ndim

2

In [20]:
a>20

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True]])

In [21]:
a[a<20]

array([ 6,  4,  2,  5,  6,  6,  7,  8,  5,  6, 11])

In [22]:
arr = np.arange(2,15,1)    #step
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
arr = np.linspace(10,1,10) #values
arr

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.])

In [24]:
arr[5:] = 100
arr

array([ 10.,   9.,   8.,   7.,   6., 100., 100., 100., 100., 100.])

In [25]:
arr==100

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [26]:
x = arr*100
x

array([ 1000.,   900.,   800.,   700.,   600., 10000., 10000., 10000.,
       10000., 10000.])

In [27]:
arr<100

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [28]:
arr[False]

array([], shape=(0, 10), dtype=float64)

In [29]:
arr[arr<100]     #elements less than 100

array([10.,  9.,  8.,  7.,  6.])

In [30]:
(np.random.rand(3,3,2)*10)

array([[[1.66938518, 2.59477266],
        [6.95481311, 0.25321918],
        [3.7531637 , 9.96230163]],

       [[5.69935455, 4.93386287],
        [2.30340877, 7.69112419],
        [2.92960778, 3.82491944]],

       [[9.78167941, 8.78529307],
        [6.5441654 , 8.11214684],
        [4.09377122, 7.35353611]]])

In [31]:
np.ones((3,5), dtype=str)

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [32]:
np.random.randint(1,40,32).reshape(2,4,2,2)

array([[[[39, 14],
         [26, 22]],

        [[34, 29],
         [25, 25]],

        [[22, 31],
         [31, 24]],

        [[ 9, 20],
         [33, 34]]],


       [[[24,  1],
         [20, 20]],

        [[ 1, 37],
         [21, 16]],

        [[ 7, 14],
         [ 5,  8]],

        [[29, 16],
         [18,  6]]]])

In [33]:
np.random.randint(1,40,16).reshape(2,4,2,1)

array([[[[15],
         [32]],

        [[10],
         [20]],

        [[21],
         [38]],

        [[37],
         [33]]],


       [[[16],
         [ 8]],

        [[39],
         [18]],

        [[19],
         [ 9]],

        [[ 1],
         [17]]]])

In [34]:
import pandas as pd

In [35]:
df = pd.DataFrame(np.arange(1,11,1).reshape(2,5),index=['r1', 'r2'], columns=['c1','c2','c3','c4','c5'])
df

c1  c2  c3  c4  c5
r1   1   2   3   4   5
r2   6   7   8   9  10

In [36]:
# df.to_csv('')

In [37]:
np.arange(1,12,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [39]:
df

c1  c2  c3  c4  c5
r1   1   2   3   4   5
r2   6   7   8   9  10

In [40]:
type(df.loc['r1'])

pandas.core.series.Series

In [41]:
df.loc['r1',['c2','c4']]

c2    2
c4    4
Name: r1, dtype: int32

In [42]:
# converting dfs to arrays -> removing the row & col indices
df.values.shape

(2, 5)

In [43]:
df.sum(axis=0)

c1     7
c2     9
c3    11
c4    13
c5    15
dtype: int64

In [44]:
df['c1'].value_counts()

1    1
6    1
Name: c1, dtype: int64

In [45]:
type(df[['c1','c4']])

pandas.core.frame.DataFrame

In [46]:
theList = [['a', 505, 'Data-science', 9.5],
 ['b', 101, 'Python', 10],
 ['c', 222, 'Mathematics', 9],
 ['d', 301, 'PHP', 7],
 ['e', 202, 'Descriptive analytics', 9],
 ['f',505, 'Business Intelligence', 10]]
df1 = pd.DataFrame(theList, columns=('rowID','subject-code', 'subject-name','score'))
df1

rowID  subject-code           subject-name  score
0     a           505           Data-science    9.5
1     b           101                 Python   10.0
2     c           222            Mathematics    9.0
3     d           301                    PHP    7.0
4     e           202  Descriptive analytics    9.0
5     f           505  Business Intelligence   10.0

In [47]:
df1['score'].unique()

array([ 9.5, 10. ,  9. ,  7. ])

In [48]:
df1[df1['score']>9]

rowID  subject-code           subject-name  score
0     a           505           Data-science    9.5
1     b           101                 Python   10.0
5     f           505  Business Intelligence   10.0

In [49]:
df1['score'][1]

10.0

In [50]:
# df=pd.read_csv(StringIO(data), dtype{'b':int, 'c':float, 'a':object})


In [51]:
import matplotlib.pyplot as plot
%matplotlib inline

In [52]:
myL1 = 'x'
myL2 = 'x'
myL1 is myL2

True

In [53]:
import numpy
np.ndarray((2,5), dtype=int)

array([[         0,          0,          0, 1070596096,          0],
       [1071644672,          0, 1072168960,          0, 1072693248]])

In [54]:
af

NameError: name 'af' is not defined

In [55]:
np.__version__

'1.22.3'

In [56]:
a = np.array([4,5])
type(a)

numpy.ndarray

In [57]:
type(a).__module__

'numpy'

In [68]:
a = np.arange(10)
c = (a <= 2) #condition

In [70]:
a[c]

array([0, 1, 2])

In [74]:
np.where(a<=2,a,0)

array([0, 1, 2, 0, 0, 0, 0, 0, 0, 0])

True